before_script: bundle exec rake db:create db:schema:load
bundler_args: "--without assets:development:production"
cache: bundler
language: ruby
rvm:
- 2.2.3
script:
- bundle exec rake
- bundle exec rubocop
sudo: false
deploy:
  provider: heroku
  api_key:
    secure: gzI1Bfic6d7vKRoNY4UkHdsJyLYc+0E6E4rs+PLHF1z3/Eg9KS8A76YfQDc4nrocr062yT7u2bb2c/4bX1C693N9wSnCCU5gmpLIOo3xdLDFmAWxhEsDM05BYsBFUSdKUpyH9ZxJVXEcgSbPVeYmpHUol48NtmSCVUiLufLF0smLkXghSb9awbdk9rfOTdscypOJsDTYS6LoKft+i6TrddkGt7rVH5A+2gC8LqRUet88Ka/9ak8nP1dNvajvjcNYcAnHBBOyXxQaSudJelZHd+gVpAQkEnWcf9q1S+koG/0Sa1wUkgnp0RLYyALFWo1Q3o3aUA0bEWgAzoc9MKFaHcioopP9zJ/uhb+mc48sS8iIy7gd+sadGbRQKaWx45si7HE/MCY1K9hRmEXMehKRGzf9jpCH5iDc3wO5eXNPTlcK/nO6Q7b9hFp0gOg3J7sRMKFmjZgGL+IKJjBa6yFI0VGXme2sG6h5/gWBERP1xtNF8wVilhlAbwwAChAXB+aye0FnLRC89eXv5lfawCqsWM+YJzed2a1X0myCCSAgej2HJFTDIcKTOa33uIwQyNS+MqBHfxSLDWB4tPe3bx+4qz30zG/7++MbDWveIsYcybfY/nmkLvp/TM8XVQtVAcgBrez0aPN//Hg2IEqEaTRIcsBD+hlT1r4gvFJ0lTQW51I=
  app: adoptadrainsf
  on:
    repo: sfbrigade/adopt-a-drain
    branch: production
